### ISSUE TITLE
File name, extensions and folders in UPPERCASE

### ISSUE THREAD

**Issue by sergiopjf** [HemanthTenneti/FileSorter#1]
Hi,

When there are files, extensions and subfolders with names in uppercase, FileSorter does not sort the files.

Thanks,

**Comment by sergiopjf** [comment]
My Solution:

`import shutil
import os
from time import sleep
from fileExtensions import commonFileTypes
import customtkinter as ctk
from tkinter import filedialog
from tkinter import messagebox

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("dark-blue")
window = ctk.CTk()
window.geometry("240x190")
window.title("File Sorter")
window.resizable(False, False)


def createFolder(parent_dir):
    global dir_list
    dir_list = os.listdir(parent_dir)
    for fileTypes in dir_list:
        fileExt = fileTypes.split(".")[-1].lower()
        if (
            fileExt in commonFileTypes
            and os.path.exists(parent_dir + "/" + commonFileTypes[fileExt]) == False
        ):
            os.mkdir(parent_dir + "/" + commonFileTypes[fileExt])


def sortFiles(parent_dir):
    for fileTypes in dir_list:
        fileExt = fileTypes.split(".")[-1].lower()
        if fileExt in commonFileTypes:
            shutil.move(
                f"{parent_dir}/{fileTypes}",
                f"{parent_dir}/{commonFileTypes[fileExt]}/{fileTypes}",
            )


def sortButton():
    if directory not in [None, ""]:
        createFolder(directory)
        sleep(0.5)
        sortFiles(directory)
        messagebox.showinfo(
            "Finished sorting", "The files in your chosen directory have been sorted"
        )
    else:
        messagebox.showwarning(
            "Something's wrong",
            "I can feel it. It was an error, you didn't specify a path.",
        )


directory = None


def directorySelectButton():
    global directory
    directory = filedialog.askdirectory(title="Selecione um diretorio")


dirButton = ctk.CTkButton(
    master=window, command=lambda: directorySelectButton(), text="Escolha o diretorio"
)
sortFilesButton = ctk.CTkButton(
    master=window, command=lambda: sortButton(), text="Organizar os arquivos"
)
dirButton.pack(pady=30, padx=10)
sortFilesButton.pack(pady=30, padx=20)


window.mainloop()

**Comment by sergiopjf** [comment]
My solution:

import shutil
import os
from time import sleep
from fileExtensions import commonFileTypes
import customtkinter as ctk
from tkinter import filedialog
from tkinter import messagebox

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("dark-blue")
window = ctk.CTk()
window.geometry("240x190")
window.title("File Sorter")
window.resizable(False, False)


def createFolder(parent_dir):
    global dir_list
    dir_list = os.listdir(parent_dir)
    for fileTypes in dir_list:
        fileExt = fileTypes.split(".")[-1]**.lower()**
        if (
            **fileExt** in commonFileTypes
            and os.path.exists(parent_dir + "/" + commonFileTypes[fileExt]) == False
        ):
            os.mkdir(parent_dir + "/" + commonFileTypes[fileExt])


def sortFiles(parent_dir):
    for fileTypes in dir_list:
        fileExt = fileTypes.split(".")[-1]**.lower()**
        if **fileExt** in commonFileTypes:
            shutil.move(
                f"{parent_dir}/{fileTypes}",
                f"{parent_dir}/{commonFileTypes[fileExt]}/{fileTypes}",
            )


def sortButton():
    if directory not in [None, ""]:
        createFolder(directory)
        sleep(0.5)
        sortFiles(directory)
        messagebox.showinfo(
            "Finished sorting", "The files in your chosen directory have been sorted"
        )
    else:
        messagebox.showwarning(
            "Something's wrong",
            "I can feel it. It was an error, you didn't specify a path.",
        )


directory = None


def directorySelectButton():
    global directory
    directory = filedialog.askdirectory(title="Select a directory")


dirButton = ctk.CTkButton(
    master=window, command=lambda: directorySelectButton(), text="Choose directory"
)
sortFilesButton = ctk.CTkButton(
    master=window, command=lambda: sortButton(), text="Sort the files"
)
dirButton.pack(pady=30, padx=10)
sortFilesButton.pack(pady=30, padx=20)


window.mainloop()

**Comment by sergiopjf** [comment]
However, there is still a bug if a folder named after an extension exists. For example folder zip, it will be considered a file and will be moved to the archive folder.

**Comment by HemanthTenneti** [comment]
Hey there! Thanks a lot for pointing these out. I've added the check for character casing. I've also taken your suggestion and implemented a check for the type of file/folder to avoid moving folders with file extensions in the name.
Also added a button in the program itself to open the selected folder!

Thanks!
Let me know of any more suggestions/bugs/changes to make it better.
